# This Makefile is generated by the made script:
# https://github.com/alx741/made
#

TASK_RUNNER=cabal
BUILD_COMMAND=$(TASK_RUNNER) build
TEST_COMMAND=$(TASK_RUNNER) test

.PHONY: build test css

build: css
	$(BUILD_COMMAND)
	$(TASK_RUNNER) exec site rebuild

css:
	cd css && $(MAKE)

test:
	$(TEST_COMMAND)

watch:
	while true; do make css; inotifywait -qre close_write css/*.sass; done

clean:
	$(TASK_RUNNER) exec site clean
	$(TASK_RUNNER) clean
